export const seedBooks = [
    {
        titulo: "Eu sou Ozzy: A autobiografia",
        sinopse: "As pessoas me perguntam como eu ainda estou vivo, e eu não sei o que dizer. Quando eu estava crescendo, se você me colocasse contra uma parede com os outros garotos da minha rua e me perguntasse qual de nós chegaria aos sessenta anos, com cinco filhos e quatro netos e casas em Buckinghamshire e Califórnia, eu não teria apostado dinheiro em mim – de jeito nenhum. Mas aqui estou eu: pronto para contar minha história, com minhas próprias palavras.",
        caminho_arquivo: "https://m.media-amazon.com/images/I/410hJcB06+L._SX315_BO1,204,203,200_.jpg",
        editora: "Belas-Letras",
        idioma: "Português",
        ano: 2021,
        autor: "Ozzy Osbourne",
        genero: "Biografia",
    },
    {
        titulo: "Harry Potter e a Pedra Filosofal",
        sinopse: "Harry Potter é um garoto cujos pais, feiticeiros, foram assassinados por um poderosíssimo bruxo quando ele ainda era um bebê. Ele foi levado, então, para a casa dos tios que nada tinham a ver com o sobrenatural. Pelo contrário. Até os 10 anos, Harry foi uma espécie de gata borralheira: maltratado pelos tios, herdava roupas velhas do primo gorducho, tinha óculos remendados e era tratado como um estorvo. No dia de seu aniversário de 11 anos, entretanto, ele parece deslizar por um buraco sem fundo, como o de Alice no país das maravilhas, que o conduz a um mundo mágico. Descobre sua verdadeira história e seu destino: ser um aprendiz de feiticeiro até o dia em que terá que enfrentar a pior força do mal, o homem que assassinou seus pais.",
        caminho_arquivo: "https://m.media-amazon.com/images/I/41897yAI4LL._SX346_BO1,204,203,200_.jpg",
        editora: "Rocco",
        idioma: "Português",
        ano: 2016,
        autor: "J.K. Rowling",
        genero: "Fantasia",
    },
    {
        titulo: "Diário de um banana 1",
        sinopse: "Greg Heffley vive no inferno. Ou seja: no sexto ano do ensino fundamental. Franzino. Greg divide os corredores de sua escola com um bando de adolescentes que já se barbeiam. Para fugir destes “malvados” e conseguir um pouco de popularidade",
        caminho_arquivo: "https://m.media-amazon.com/images/I/51fn5ioe+dL._SX337_BO1,204,203,200_.jpg",
        editora: "VR Editora",
        idioma: "Português",
        ano: 2008,
        autor: "Jeff Kinney",
        genero: "Ficção",
    },
    {
        titulo: "É Assim que Acaba",
        sinopse: "Em É assim que acaba, Colleen Hoover nos apresenta Lily, uma jovem que se mudou de uma cidadezinha do Maine para Boston, se formou em marketing e abriu a própria floricultura. E é em um dos terraços de Boston que ela conhece Ryle, um neurocirurgião confiante, teimoso e talvez até um pouco arrogante, com uma grande aversão a relacionamentos, mas que se sente muito atraído por ela        Quando os dois se apaixonam, Lily se vê no meio de um relacionamento turbulento que não é o que ela esperava. Mas será que ela conseguirá enxergar isso, por mais doloroso que seja",
        caminho_arquivo: "https://m.media-amazon.com/images/I/51i7kH+rh9L._SX322_BO1,204,203,200_.jpg",
        editora: "Galera",
        idioma: "Português",
        ano:2018,
        autor: "Colleen Hoover",
        genero: "Romance",
    },
    {
        titulo: "É assim que começa",
        sinopse: "Quando Lily esbarra em Atlas ― com quem não fala há quase dois anos ―, parece que finalmente chegou o momento de retomar o relacionamento da adolescência, já que ele também está solteiro e parece retribuir os sentimentos de Lily. Mas apesar de divorciada, Lily não está exatamente livre de Ryle. Culpando Atlas pelo fim de seu casamento, Ryle não está nada disposto a aceitar o novo relacionamento de Lily, ainda mais com Atlas, o último homem que aceitaria ver perto de sua filha e da ex-esposa.",
        caminho_arquivo: "https://m.media-amazon.com/images/I/51jiQtSEwDL._SX327_BO1,204,203,200_.jpg",
        editora: "Galera",
        idioma: "Português",
        ano: 2022,
        autor: "Colleen Hoover",
        genero: "Romance",
    },
    {
        titulo: "Trono de vidro",
        sinopse: "Aos 18 anos uma prisioneira está cumprindo sua sentença. Ela é uma assassina, e a melhor de Adarlan. Aprisionada e fraca, ela está quase perdendo as esperanças, a sentença de morte é iminente, mas a jovem recebe uma proposta inesperada: representar o príncipe em uma competição com lutando contra os mais habilidosos assassinos e larápios do reino. Mas ela não diz sim apenas para matar, seu foco é obter sua liberdade de volta.",
        caminho_arquivo: "https://m.media-amazon.com/images/I/41rtnHT5SsL._SX335_BO1,204,203,200_.jpg",
        editora: "Galera",
        idioma: "Português",
        ano: 2013,
        autor: "Sarah J. Maas",
        genero: "Fantasia",
    },
]

export const seedUsers = [
    {
        email: "teste1@teste.teste",
        data_nascimento: "2001/12/09",
        sexo: "m",
        nome: "teste1",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "teste2@teste.teste",
        data_nascimento: "2002/01/19",
        sexo: "f",
        nome: "teste2",
        senha: "teste321",
        isAdmin: false,
    },
    {
        email: "roberto@teste.teste",
        data_nascimento: "1990/12/09",
        sexo: "m",
        nome: "roberto",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "josimar@teste.teste",
        data_nascimento: "1965/04/21",
        sexo: "m",
        nome: "josimar",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "alice@teste.teste",
        data_nascimento: "2002/07/21",
        sexo: "f",
        nome: "alice",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "marcia@teste.teste",
        data_nascimento: "1987/11/09",
        sexo: "f",
        nome: "marcia",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "roberta@teste.teste",
        data_nascimento: "2001/12/09",
        sexo: "f",
        nome: "roberta",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "romário@teste.teste",
        data_nascimento: "199/05/01",
        sexo: "m",
        nome: "romário",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "pikachu@teste.teste",
        data_nascimento: "2004/08/19",
        sexo: "m",
        nome: "pikachu",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "brenda@teste.teste",
        data_nascimento: "2003/01/11",
        sexo: "f",
        nome: "brenda",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "rodrigo@teste.teste",
        data_nascimento: "2002/10/10",
        sexo: "m",
        nome: "rodrigo",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "admin@admin.admin",
        data_nascimento: "2000/11/09",
        sexo: "m",
        nome: "admin",
        senha: "admin123",
        isAdmin: true,
    },
    {
        email: "carolina@teste.teste",
        data_nascimento: "2003/09/12",
        sexo: "f",
        nome: "carolina",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "britney@teste.teste",
        data_nascimento: "1997/04/19",
        sexo: "f",
        nome: "britney",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "joão@teste.teste",
        data_nascimento: "2001/12/09",
        sexo: "m",
        nome: "joão",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "flávia@teste.teste",
        data_nascimento: "2002/12/29",
        sexo: "f",
        nome: "flávia",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "matheus@teste.teste",
        data_nascimento: "2000/09/20",
        sexo: "m",
        nome: "matheus",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "marcus@teste.teste",
        data_nascimento: "2003/06/14",
        sexo: "m",
        nome: "marcus",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "gianluca@teste.teste",
        data_nascimento: "2003/06/12",
        sexo: "m",
        nome: "gianluca",
        senha: "teste123",
        isAdmin: false,
    },

]