export const seedBooks = [
    {
        titulo: "Eu sou Ozzy: A autobiografia",
        sinopse: "As pessoas me perguntam como eu ainda estou vivo, e eu não sei o que dizer. Quando eu estava crescendo, se você me colocasse contra uma parede com os outros garotos da minha rua e me perguntasse qual de nós chegaria aos sessenta anos, com cinco filhos e quatro netos e casas em Buckinghamshire e Califórnia, eu não teria apostado dinheiro em mim – de jeito nenhum. Mas aqui estou eu: pronto para contar minha história, com minhas próprias palavras.",
        caminho_arquivo: "https://m.media-amazon.com/images/I/410hJcB06+L._SX315_BO1,204,203,200_.jpg",
        editora: "Belas-Letras",
        idioma: "Português",
        ano: new Date(2021).getFullYear,
        autor: "Ozzy Osbourne",
        genero: "Biografia",
    },
    {
        titulo: "Harry Potter e a Pedra Filosofal",
        sinopse: "Harry Potter é um garoto cujos pais, feiticeiros, foram assassinados por um poderosíssimo bruxo quando ele ainda era um bebê. Ele foi levado, então, para a casa dos tios que nada tinham a ver com o sobrenatural. Pelo contrário. Até os 10 anos, Harry foi uma espécie de gata borralheira: maltratado pelos tios, herdava roupas velhas do primo gorducho, tinha óculos remendados e era tratado como um estorvo. No dia de seu aniversário de 11 anos, entretanto, ele parece deslizar por um buraco sem fundo, como o de Alice no país das maravilhas, que o conduz a um mundo mágico. Descobre sua verdadeira história e seu destino: ser um aprendiz de feiticeiro até o dia em que terá que enfrentar a pior força do mal, o homem que assassinou seus pais.",
        caminho_arquivo: "https://m.media-amazon.com/images/I/41897yAI4LL._SX346_BO1,204,203,200_.jpg",
        editora: "Rocco",
        idioma: "Português",
        ano: new Date(2016).getFullYear,
        autor: "J.K. Rowling",
        genero: "Fantasia",
    },
    {
        titulo: "Harry Potter e a Camara Secreta",
        sinopse: "De férias na casa de seus tios, Harry Potter recebe a inesperada visita de Dobby, um elfo doméstico, que veio avisá-lo para não retornar à Escola de Magia de Hogwarts, pois lá correrá um grande perigo. Harry não lhe dá ouvidos e decide retornar aos estudos, enfrentando um 2º ano recheado de novidades. Uma delas é a contratação do novo Professor de Defesa Contra as Artes das Trevas, Gilderoy Lockhart, que é considerado um grande galã e não perde uma oportunidade de fazer marketing pessoal. Porém, o aviso de Dobby se confirma e logo toda Hogwarts está envolvida em um mistério que resulta no aparecimento de alunos petrificados.",
        caminho_arquivo: "https://i.pinimg.com/564x/cd/5e/28/cd5e286a0af2cf3a2a82a04d37bfd575.jpg",
        editora: "Rocco",
        idioma: "Português",
        ano: new Date(2001).getFullYear,
        autor: "J.K. Rowling",
        genero: "Fantasia",
    },
]

export const seedUsers = [
    {
        email: "teste1@teste.teste",
        data_nascimento: "2001/12/09",
        sexo: "m",
        nome: "teste1",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "teste2@teste.teste",
        data_nascimento: "2002/01/19",
        sexo: "f",
        nome: "teste2",
        senha: "teste321",
        isAdmin: false,
    },
    {
        email: "roberto@teste.teste",
        data_nascimento: "1990/12/09",
        sexo: "m",
        nome: "roberto",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "josimar@teste.teste",
        data_nascimento: "1965/04/21",
        sexo: "m",
        nome: "josimar",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "alice@teste.teste",
        data_nascimento: "2002/07/21",
        sexo: "f",
        nome: "alice",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "marcia@teste.teste",
        data_nascimento: "1987/11/09",
        sexo: "f",
        nome: "marcia",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "roberta@teste.teste",
        data_nascimento: "2001/12/09",
        sexo: "f",
        nome: "roberta",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "romário@teste.teste",
        data_nascimento: "199/05/01",
        sexo: "m",
        nome: "romário",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "pikachu@teste.teste",
        data_nascimento: "2004/08/19",
        sexo: "m",
        nome: "pikachu",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "brenda@teste.teste",
        data_nascimento: "2003/01/11",
        sexo: "f",
        nome: "brenda",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "rodrigo@teste.teste",
        data_nascimento: "2002/10/10",
        sexo: "m",
        nome: "rodrigo",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "admin@admin.admin",
        data_nascimento: "2000/11/09",
        sexo: "m",
        nome: "admin",
        senha: "admin123",
        isAdmin: true,
    },
    {
        email: "carolina@teste.teste",
        data_nascimento: "2003/09/12",
        sexo: "f",
        nome: "carolina",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "britney@teste.teste",
        data_nascimento: "1997/04/19",
        sexo: "f",
        nome: "britney",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "joão@teste.teste",
        data_nascimento: "2001/12/09",
        sexo: "m",
        nome: "joão",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "flávia@teste.teste",
        data_nascimento: "2002/12/29",
        sexo: "f",
        nome: "flávia",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "matheus@teste.teste",
        data_nascimento: "2000/09/20",
        sexo: "m",
        nome: "matheus",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "marcus@teste.teste",
        data_nascimento: "2003/06/14",
        sexo: "m",
        nome: "marcus",
        senha: "teste123",
        isAdmin: false,
    },
    {
        email: "gianluca@teste.teste",
        data_nascimento: "2003/06/12",
        sexo: "m",
        nome: "gianluca",
        senha: "teste123",
        isAdmin: false,
    },

]