export const seedBooks ={

} 

export const seedUsers =[
    {     
        email:"teste1@teste.teste",    
        data_nascimento: "2001/12/09",
        sexo:"m",
        nome:"teste1",           
        senha:"teste123",         
        isAdmin:false,        
    },
    {     
        email:"teste2@teste.teste",    
        data_nascimento: "2002/01/19",
        sexo:"f",
        nome:"teste2",           
        senha:"teste321",         
        isAdmin:false,        
    },
    {     
        email:"roberto@teste.teste",    
        data_nascimento: "1990/12/09",
        sexo:"m",
        nome:"roberto",           
        senha:"teste123",         
        isAdmin:false,        
    },
    {     
        email:"josimar@teste.teste",    
        data_nascimento: "1965/04/21",
        sexo:"m",
        nome:"josimar",           
        senha:"teste123",         
        isAdmin:false,        
    },
    {     
        email:"alice@teste.teste",    
        data_nascimento: "2002/07/21",
        sexo:"f",
        nome:"alice",           
        senha:"teste123",         
        isAdmin:false,        
    },
    {     
        email:"marcia@teste.teste",    
        data_nascimento: "1987/11/09",
        sexo:"f",
        nome:"marcia",           
        senha:"teste123",         
        isAdmin:false,        
    },
    {     
        email:"roberta@teste.teste",    
        data_nascimento: "2001/12/09",
        sexo:"f",
        nome:"roberta",           
        senha:"teste123",         
        isAdmin:false,        
    },
    {     
        email:"romário@teste.teste",    
        data_nascimento: "199/05/01",
        sexo:"m",
        nome:"romário",           
        senha:"teste123",         
        isAdmin:false,        
    },
    {     
        email:"pikachu@teste.teste",    
        data_nascimento: "2004/08/19",
        sexo:"m",
        nome:"pikachu",           
        senha:"teste123",         
        isAdmin:false,        
    },
    {     
        email:"brenda@teste.teste",    
        data_nascimento: "2003/01/11",
        sexo:"f",
        nome:"brenda",           
        senha:"teste123",         
        isAdmin:false,        
    },
    {     
        email:"rodrigo@teste.teste",    
        data_nascimento: "2002/10/10",
        sexo:"m",
        nome:"rodrigo",           
        senha:"teste123",         
        isAdmin:false,        
    },
    {     
        email:"admin@admin.admin",    
        data_nascimento: "2000/11/09",
        sexo:"m",
        nome:"admin",           
        senha:"admin123",         
        isAdmin:true,        
    },
    {     
        email:"carolina@teste.teste",    
        data_nascimento: "2003/09/12",
        sexo:"f",
        nome:"carolina",           
        senha:"teste123",         
        isAdmin:false,        
    },
    {     
        email:"britney@teste.teste",    
        data_nascimento: "1997/04/19",
        sexo:"f",
        nome:"britney",           
        senha:"teste123",         
        isAdmin:false,        
    },
    {     
        email:"joão@teste.teste",    
        data_nascimento: "2001/12/09",
        sexo:"m",
        nome:"joão",           
        senha:"teste123",         
        isAdmin:false,        
    },
    {     
        email:"flávia@teste.teste",    
        data_nascimento: "2002/12/29",
        sexo:"f",
        nome:"flávia",           
        senha:"teste123",         
        isAdmin:false,        
    },
    {     
        email:"matheus@teste.teste",    
        data_nascimento: "2000/09/20",
        sexo:"m",
        nome:"matheus",           
        senha:"teste123",         
        isAdmin:false,        
    },
    {     
        email:"marcus@teste.teste",    
        data_nascimento: "2003/06/14",
        sexo:"m",
        nome:"marcus",           
        senha:"teste123",         
        isAdmin:false,        
    },
    {     
        email:"gianluca@teste.teste",    
        data_nascimento: "2003/06/12",
        sexo:"m",
        nome:"gianluca",           
        senha:"teste123",         
        isAdmin:false,        
    },

]